### PR TITLE
Add OneClick setup, Add Big Sur and Monterey support, upgrade ESP.qcow2 to OpenCore, Fix macOS fetching, Fix mouse

### PR DESCRIPTION
**Pull request by notAperson535**
This adds some changes that make the macOS-Simple-KVM experience smoother and better

### CODE REVIEW

**Comment by alexeyneu** [comment]
so where current stuff with clover loads el capitan yours doesn't

**Comment by notAperson535** [comment]
@alexeyneu Why would it not work? Can you test it for me using this repo: https://github.com/notAperson535/OneClick-macOS-Simple-KVM If it doesn't work tell me, and I will fix it.

**Comment by notAperson535** [comment]
> 

@alexeyneu no actually, Opencore works better for legacy macOS and can go back to 10.4

**Comment by meow464** [comment]
I was able to install Monterey using this. So far it's stable. I couldn't get it to work with OSX-KVM (probably my fault) and it runs better than Big Sur on VirtualBox.

**Comment by notAperson535** [comment]
@meow464 Nice! And you're right. It is more stable than OSX-KVM

**Comment by notAperson535** [comment]
I am taking this pull request down and making a new one you can access all these changes here: https://notaperson535.github.io/OneClick-macOS-Simple-KVM/

**Pull request closed without merging**
