### PR TITLE
Add instructions for Solus OS

### PR DESCRIPTION
**Pull request by koyuawsmbrtn**
Confirmed to be working well on Solus, so posting my findings here.

### CODE REVIEW

**Comment by mjarkk** [comment]
Can confirm this works just tried it  
Though it seems like python 3 is already pre installed in solus

**Comment by koyuawsmbrtn** [comment]
It is, I'll remove it then

**Comment by koyuawsmbrtn** [comment]
If nobody wants to merge it then okay

**Comment by foxlet** [comment]
Sorry, I try to test all the changes made to the repo, and unfortunately that means some commits get backlogged.

**Pull request closed without merging**
