### PR TITLE
Add note about automatic internet to networking.md

### PR DESCRIPTION
**Pull request by LukasKalbertodt**
So I wasted 1,5 hours trying to make bridged networking work just
to get internet access in MacOS. I thought I didn't have internet in
the VM because I tried to `ping 1.1.1.1`. Hopefully this note can
help future users not to waste their time, too.

### CODE REVIEW

**Comment by gfxpr0** [comment]
@LukasKalbertodt: ICMP does not work in QEMU. Read more about it https://wiki.qemu.org/Documentation/Networking.

**Comment by foxlet** [comment]
It's `basic.sh`, not `simple.sh`.

**Comment by LukasKalbertodt** [comment]
@foxlet Fixed.

**Comment by foxlet** [comment]
Squash the commits with a `[DOCS]` tag and we should be good. :+1:

**Comment by LukasKalbertodt** [comment]
@foxlet  Sorry for the delay, was on vacation. Should be fine now!

**Pull request merged**
