### PR TITLE
Updated for Big Sur and Monterey

### PR DESCRIPTION
**Pull request by SomeoneAlt-86**

### CODE REVIEW

**Comment by itamarjp** [comment]
looks good, if don't break old versions download then please commit.

**Comment by mgorny** [comment]
Hardcoding `sudo apt-get` calls breaks it for every non-Debian system out there.

**Comment by notAperson535** [comment]
@SomeoneAlt-86 I think mine does it better: https://github.com/notAperson535/OneClick-macOS-Simple-KVM
It also has a one click setup

**Comment by notAperson535** [comment]
@SomeoneAlt-86  this does not actually fix the loading of the operating systems, just downloads them

**Comment by SomeoneAlt-86** [comment]
@notAperson535 OS loads just fine there's no need to fix them , Original does not support Big Sur and Monterey for downloads which this commit fixes

**Comment by notAperson535** [comment]
@SomeoneAlt-86 clover can't load big sur or monterey

**Comment by SomeoneAlt-86** [comment]
@notAperson535 Alright I am giving up to you.

**Pull request closed without merging**
